baseURL = 'https://hanatomizu.github.io/blog/'
languageCode = 'en-us'
title = 'Chinen Natsuyo | Website'
theme = 'github-style'

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Hanatomizu"
  description = "永遠なんてないけど、思い通りの日々じゃないけど、脆く弱い糸に繋がれた、次の夜明けがまだ訪れる。"
  github = "Hanatomizu"
  email = "chart11from21@outlook.com"
  url = "https://hanatomizu.github.io/blog"
  keywords = "blog"
  rss = false
  lastmod = false
  userStatusEmoji = ""
  favicon = "/blog/images/github-mark.png"
  avatar = "/blog/images/hanatomizu.png"
  headerIcon = "/blog/images/github-mark-white.png"
  location = "Universe"
  enableGitalk = false

