baseURL = 'https://hanatomizu.github.io/blog/'
languageCode = 'en-us'
title = 'Chinen Natsuyo | Website'
theme = 'github-style'

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Hanatomizu"
  description = "When life gives you lemon, don't make lemonade, make life take the lemons back."
  github = "Hanatomizu"
  email = "chart11from21@outlook.com"
  url = "https://hanatomizu.github.io/blog"
  keywords = "blog"
  rss = false
  lastmod = false
  userStatusEmoji = "😀"
  favicon = "/blog/images/github-mark.png"
  avatar = "/blog/images/hanatomizu.png"
  headerIcon = "/blog/images/github-mark-white.png"
  location = "Universe"
  enableGitalk = false

