#!/bin/sh

if [ "`git status -s`" ]
then
    echo "The working directory is dirty. Please commit any pending changes."
    exit 1;
fi

echo "Deleting old publication"
rm -rf public
mkdir public
git worktree prune
rm -rf .git/worktrees/public/

echo "Checking out gh-pages branch into public"
git worktree add -B gh-pages public origin/gh-pages

echo "Removing existing files"
rm -rf public/*

echo "Generating site"
env HUGO_ENV="production" hugo -t github-style

echo "Updating LICENSE"
cp LICENSE public/LICENSE

echo "Adding action support"
cp .github/workflows/deploy.yaml public/.github/workflows/deploy.yaml

echo "Updating gh-pages branch"
cd public && git add --all && git commit -S -m "Publishing to gh-pages ($(git log --all --oneline -n 1 --format=%h))
Master orinal version: $(git log --all --oneline -n 1 --format=%H%n%s)"

#echo "Pushing to github"
#git push --all
